version = 0.1

[default.deploy.parameters]
stack_name = "solar-admin-api-prod"
resolve_s3 = true
s3_prefix = "solar-admin-api-prod"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = [
    "AwsRegion=us-east-2",
    "CognitoUserPoolId=us-east-2_a98WW3Z3T",
    "CognitoClientId=6j57c6dts56j4gn0ctpokgob63",
    "ProjectsTableDev=solar-projects-dev",
    "ProjectsTableProd=solar-projects-prod",
    "GroundtruthBucketDev=solar-groundtruth-dev",
    "GroundtruthBucketProd=solar-groundtruth-prod",
    "OrthosBucketDev=solar-orthos-dev",
    "OrthosBucketProd=solar-orthos-prod",
    "ReportsBucketDev=solar-reports-dev",
    "ReportsBucketProd=solar-reports-prod",
    "ReportJobDefinitionDev=solar-report-dev",
    "ReportJobDefinitionProd=solar-report-prod",
    "InferenceJobDefinitionDev=solar-inference-dev",
    "InferenceJobDefinitionProd=solar-inference-prod",
    "JobQueueDev=solar-job-queue-dev",
    "JobQueueProd=solar-job-queue-prod",
    "TrainingDataBucket=solar-ai-training",
    "ModelRegistryTable=solar-model-registry-prod",
    "ProdModelPrefix=model-registry",
    "ModelRegistryProdPointerPk=MODEL#PROD_POINTER",
    "CocoJobDefinition=solar-detectron2-training-gpu:1",
    "CocoJobQueue=solar-gpu-queue-v2",
    "RetrainJobDefinition=solar-detectron2-training-gpu:1",
    "RetrainJobQueue=solar-gpu-queue-v2",
    "SenderEmail=noreply@aisol.cloud",
    "ELUploadsBucketDev=solar-el-uploads-dev",
    "ELUploadsBucketProd=solar-el-uploads-prod",
    "ELGroundtruthBucketDev=solar-el-groundtruth-dev",
    "ELGroundtruthBucketProd=solar-el-groundtruth-prod",
    "ELReportsBucketDev=solar-el-reports-dev",
    "ELReportsBucketProd=solar-el-reports-prod",
    "ELReportJobDefinitionDev=solar-el-report-dev",
    "ELReportJobDefinitionProd=solar-el-report-prod",
    "ELInferenceMode=batch",
    "ELModelRegistryTable=solar-el-model-registry-prod",
    "ELTrainingJobQueue=solar-job-queue-prod",
    "ELTrainingJobDefinition=solar-el-training",
    "IVUploadsBucketDev=solar-iv-uploads-dev",
    "IVUploadsBucketProd=solar-iv-uploads-prod",
    "IVReportsBucketDev=solar-iv-reports-dev",
    "IVReportsBucketProd=solar-iv-reports-prod",
    "IVReportJobDefinitionDev=solar-iv-report-dev",
    "IVReportJobDefinitionProd=solar-iv-report-prod",
]
